Random felhasználó generálása  :
<form action="/admin/generate" method="post">
    <select name="darab">
        <?php for ($i = 1; $i <= 100; $i++): ?>
            <option value="<?= $i ?>"><?= $i ?></option>
        <?php endfor; ?>
    </select>
    <input id="gomb" type="submit">
</form>
<?php foreach($this->uAdatok as $adatok): $date = DateTime::createFromFormat('Y M j H:i:s',$adatok->regDate);?>
    <?php if($date->format("Y M j H:i") == date("Y M j H:i")):  ?>
        Név:<?=$adatok->username ?><br/>
        Email:<?=$adatok->email ?><br/>
        RegDate:<?=$adatok->regDate ?><br/>
        Súly:<?=$adatok->weight ?><br/>
        Magasság:<?=$adatok->height ?><br/><br/>
    <?php endif; ?>
<?php endforeach;?>
