Random felhasználó generálása  :
<form action="/admin/generate" method="post">
    <select name="darab">
        <?php for ($i = 1; $i <= 100; $i++): ?>
            <option value="<?= $i ?>"><?= $i ?></option>
        <?php endfor; ?>
    </select>
    <input id="gomb" type="submit">
</form>
<?php foreach($this->uAdatok as $adatok):;?>
    <?php if($adatok->regDate == date("Y-m-d")):  ?>
        Név:<?=$adatok->username ?><br/>
        Email:<?=$adatok->email ?><br/>
        RegDate:<?=$adatok->regDate ?><br/>
        Súly:<?=$adatok->weight ?><br/>
        Magasság:<?=$adatok->height ?><br/>
        születésnap:<?=$adatok->bday ?></br></br>
    <?php endif; ?>
<?php endforeach;?>
