<div id="main">
    <form action="/chat/comment" method="post">
        <table>
            <tr>
                <!-- <td> Név:</td> <td><input placeholder="Név..." type="text" name="hBy" required/><td> !-->
            </tr>

            <tr>
                <td> Komment:</td>
                <td><input type="text" name="msg" required/></td>
                <td></td>
                <td><input type=submit name=submit></td>
            </tr>

        </table>
    </form>
    <h3>Megírt Komment:</h3></br>
</div>
<table>
    <?php foreach ($this->comment as $comments):; ?>
        <tr>
            <td>
                <h4><?= $comments->commenterUserName ?></h4>
                <?= $comments->msg ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

