<html>
<head>
    <link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
</head>
<body>
<form action="/login/belep" method="post">
    <input type="text" name="email" placeholder="email">
    <input type="password" name="pass" placeholder="Jelszó"><br>
    <input class="btn btn-default navbar-btn" value="Login" type="submit">
</form>
<a href="/register/index" type="button" class="btn btn-default navbar-btn">Regisztráció</a>


<script src="/public/js/jquery-3.1.1.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>


</body>
</html>
