<spam>Lakhely: </spam><?=$this->adat['city']?></br>
<spam>Iskola: </spam><?=$this->adat['school']?></br>
<spam>Munkahely:</spam><?=$this->adat['job']?></br>
<spam>Kit keresel: </spam><?=$this->adat['looking']?></br>
<spam>gender: </spam><?=$this->adat['gender']?></br>
<spam>bday: </spam><?=$this->adat['bday']?></br>
<spam>tol:</spam><?=$this->adat['tol']?></br>
<spam>ig: </spam><?=$this->adat['ig']?></br>
<form action="/profile/like" method="post">
    <input value="Like" type="submit">
</form>

<div id="test">asdasd</div><div class="result"></div>