<spam>Lakhely: </spam><?=$this->adat['city']?></br>
<spam>Munkahely: </spam><?=$this->adat['job']?></br>
<spam>Iskola: </spam><?=$this->adat['school']?></br>
<spam>születésnap: </spam><?=$this->adat['bday']?></br>
<spam>Magasság: </spam><?=$this->adat['height']?></br>
<spam>Súly: </spam><?=$this->adat['weight']?></br>
<spam>Szemszín: </spam><?=$this->adat['eColor']?></br>
<spam>Hajszín: </spam><?=$this->adat['hColor']?></br>
<spam>Dohányzás: </spam><?=$this->adat['smoking']?></br>
<spam>Külső: </spam><?=$this->adat['looklike']?></br>
<spam>Gyerek: </spam><?=$this->adat['hChild']?></br>
<form action="/profile/like" method="post">
    <input value="Like" type="submit">
</form>