<html>
<head>
    <link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
</head>
<body>


<a>Lakhely: </a></br>
<a>Iskola: </a></br>
<a>Munkahely: </a></br>
<a>Kapcsolati státusz: </a></br>

<form action="/profile/like" method="post">
    <input value="Like" type="submit">
</form>

<form action="/profile/dislike" method="post">
    <input value="dislike" type="submit">
</form>

    <a>Index:</a>
</body>
</html>