<html>
<head>
    <link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
</head>
<body>
<form action="/register/bekuld" method="post">
    Name: <input type="text" name="name"><br>
    E-mail: <input type="text" name="email"><br>
    Password: <input type="password" name="pass"><br>
    Password újra: <input type="password" name="pass2"><br>
    <input type="submit">
</form>
<a href="/login" type="button" class="btn btn-default navbar-btn">Login</a>


<script src="/public/js/jquery-3.1.1.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>


</body>
</html>

