<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
        <link rel="stylesheet" type="text/css" href="/public/css/mystyle.css">
    </head>
        <body>
            <form action="/register/bekuld" method="post">
                Name: <input type="text" id="name" name="name"><br>
                E-mail: <input type="email" id="email" name="email"><br>
                Password: <input type="password" id="pass" name="pass"><br>
                Password újra: <input type="password" id="pass2" name="pass2"><br>
                Neme:
                    <select name="gender">
                    <option value="no">Nő</option>
                    <option value="ferfi">Férfi</option>
                </select>
                </br>Kor:
                    <input type="date" name="bday">
                </br>Kit keresel:
                <select name="looking">
                    <option value="not">Nőt</option>
                    <option value="ferfit">Férfit</option>
                </select>
                    tól
                <select name="tol">
                    <?php for ($i = 18; $i <= 100; $i++): ?>
                        <option value="<?= $i ?>"><?= $i ?></option>
                    <?php endfor; ?>
                </select>
                -
                <select name="ig">
                    <?php for ($i = 18; $i <= 100; $i++): ?>
                        <option value="<?= $i ?>"><?= $i ?></option>
                    <?php endfor; ?>
                </select>
                ig
                </br>
                <input id="gomb" type="submit">
            </form>
            <a href="/login" type="button"  class="btn btn-default navbar-btn">Login</a>


            <script src="/public/js/jquery-3.1.1.min.js"></script>
            <script src="/public/js/bootstrap.min.js"></script>
            <script src="/public/js/check.js"></script>


        </body>
</html>

