
<form action="/register/bekuld" method="post">
    Name: <input type="text" id="name" name="name"><br>
    E-mail: <input type="email" id="email" name="email"><br>
    Password: <input type="password" id="pass" name="pass"><br>
    Password újra: <input type="password" id="pass2" name="pass2"><br>
    Neme:
    <select name="gender">
        <option value="no">Nő</option>
        <option value="ferfi">Férfi</option>
    </select>
    </br>Kor:
    <input type="date" name="bday">
    </br>Kit keresel:
    <select name="looking">
        <option value="not">Nőt</option>
        <option value="ferfit">Férfit</option>
    </select>
    tól
    <select name="tol">
        <?php for( $i=18; $i<=100;$i++):?>
            <option value="<?=$i?>"><?=$i?></option>
        <?php endfor;?>
    </select>
    -
    <select name="ig">
        <?php for( $i=18; $i<=100;$i++):?>
            <option value="<?=$i?>"><?=$i?></option>
        <?php endfor;?>
    </select>
    ig
    </br>
    <input id="gomb" type="submit">
</form>
