<html>
<head>
    <link rel="stylesheet" type="text/css" href="/public/css/bootstrap.min.css">
</head>
<body>
<form action="/settings/bekuld" method="post">
    Lakhely: <input type="text" name="city"><br>
    Munka: <input type="text" name="job"><br>
    Iskola: <input type="text" name="school"><br>
    Családi állapot: <input type="text" name="relationship"><br>
    <input type="submit">
</form>


<script src="/public/js/jquery-3.1.1.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>


</body>
</html>